#!/usr/bin/env python3
import sys
from intelhex import IntelHex

if len(sys.argv) < 4 or sys.argv[1] != '-m' or '-o' not in sys.argv:
    print("Usage: mergehex -m <file1> <file2> [...] -o <output>")
    sys.exit(1)

args = sys.argv[2:]
out_index = args.index('-o')
inputs = args[:out_index]
out_file = args[out_index + 1]

merged = IntelHex()
for f in inputs:
    merged.merge(IntelHex(f), overlap='replace')
merged.write_hex_file(out_file)
